
<?php


$videos[] = '<embed src="http://video.ted.com/assets/player/swf/EmbedPlayer.swf" pluginspace="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" wmode="transparent" bgColor="#ffffff" width="446" height="326" allowFullScreen="true" allowScriptAccess="always" flashvars="vu=http://video.ted.com/talks/dynamic/BillGates_2009-medium.flv&su=http://images.ted.com/images/ted/tedindex/embed-posters/BillGates_2009.embed_thumbnail.jpg&vw=432&vh=240&ap=0&ti=451&lang=eng&introDuration=15330&adDuration=4000&postAdDuration=830&adKeys=talk=bill_gates_unplugged;year=2009;theme=speaking_at_ted2009;theme=a_taste_of_ted2011;theme=not_business_as_usual;theme=tales_of_invention;theme=rethinking_poverty;event=Rethinking+Poverty;tag=Business;tag=Science;tag=TED2009;tag=Technology;tag=education;tag=health;tag=illness;tag=philanthropy;"></embed>';

$videos[] = '<embed src="http://video.ted.com/assets/player/swf/EmbedPlayer.swf" pluginspace="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" wmode="transparent" bgColor="#ffffff" width="446" height="326" allowFullScreen="true" allowScriptAccess="always" flashvars="vu=http://video.ted.com/talk/stream/2011/Blank/MikeMatas_2011-320k.mp4&su=http://images.ted.com/images/ted/tedindex/embed-posters/MikeMatas-2011.embed_thumbnail.jpg&vw=432&vh=240&ap=0&ti=1134&lang=eng&introDuration=15330&adDuration=4000&postAdDuration=830&adKeys=talk=mike_matas;year=2011;theme=new_on_ted_com;theme=the_creative_spark;theme=what_s_next_in_tech;theme=a_taste_of_ted2011;theme=words_about_words;event=Words+About+Words;tag=Design;tag=Entertainment;tag=Technology;tag=demo;tag=software;"></embed>';

$videos[] = '<embed src="http://video.ted.com/assets/player/swf/EmbedPlayer.swf" pluginspace="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" wmode="transparent" bgColor="#ffffff" width="446" height="326" allowFullScreen="true" allowScriptAccess="always" flashvars="vu=http://video.ted.com/talk/stream/2011/Blank/KathrynSchulz_2011-320k.mp4&su=http://images.ted.com/images/ted/tedindex/embed-posters/KathrynSchulz-2011.embed_thumbnail.jpg&vw=432&vh=240&ap=0&ti=1126&lang=eng&introDuration=15330&adDuration=4000&postAdDuration=830&adKeys=talk=kathryn_schulz_on_being_wrong;year=2011;theme=how_the_mind_works;theme=master_storytellers;theme=a_taste_of_ted2011;theme=new_on_ted_com;event=New+on+TED.com;tag=Culture;tag=failure;"></embed>';

$videos[] = '<embed src="http://video.ted.com/assets/player/swf/EmbedPlayer.swf" pluginspace="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" wmode="transparent" bgColor="#ffffff" width="446" height="326" allowFullScreen="true" allowScriptAccess="always" flashvars="vu=http://video.ted.com/talk/stream/2011/Blank/HarveyFineberg_2011-320k.mp4&su=http://images.ted.com/images/ted/tedindex/embed-posters/HarveyFineberg-2011.embed_thumbnail.jpg&vw=432&vh=240&ap=0&ti=1131&lang=eng&introDuration=15330&adDuration=4000&postAdDuration=830&adKeys=talk=harvey_fineberg_are_we_ready_for_neo_evolution;year=2011;theme=new_on_ted_com;theme=evolution_s_genius;theme=a_taste_of_ted2011;theme=medicine_without_borders;theme=technology_history_and_destiny;event=Technology%2C+History+and+Destiny;tag=Science;tag=Technology;tag=evolution;tag=medicine;tag=philosophy;"></embed>';

$videos[] = '<embed src="http://video.ted.com/assets/player/swf/EmbedPlayer.swf" pluginspace="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" wmode="transparent" bgColor="#ffffff" width="446" height="326" allowFullScreen="true" allowScriptAccess="always" flashvars="vu=http://video.ted.com/talk/stream/2011/Blank/JohnHunter_2011-320k.mp4&su=http://images.ted.com/images/ted/tedindex/embed-posters/JohnHunter-2011.embed_thumbnail.jpg&vw=432&vh=240&ap=0&ti=1127&lang=eng&introDuration=15330&adDuration=4000&postAdDuration=830&adKeys=talk=john_hunter_on_the_world_peace_game;year=2011;theme=how_we_learn;theme=the_rise_of_collaboration;theme=master_storytellers;theme=design_like_you_give_a_damn;theme=tales_of_invention;theme=a_taste_of_ted2011;theme=rethinking_poverty;theme=the_creative_spark;event=The+Creative+Spark;tag=Design;tag=Global+Issues;tag=education;tag=games;tag=government;tag=peace;tag=politics;tag=war;"></embed>';

$videos[] = '<embed src="http://video.ted.com/assets/player/swf/EmbedPlayer.swf" pluginspace="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" wmode="transparent" bgColor="#ffffff" width="446" height="326" allowFullScreen="true" allowScriptAccess="always" flashvars="vu=http://video.ted.com/talk/stream/2011/Blank/StanleyMcChrystal_2011-320k.mp4&su=http://images.ted.com/images/ted/tedindex/embed-posters/StanleyMcChrystal-2011.embed_thumbnail.jpg&vw=432&vh=240&ap=0&ti=1112&lang=eng&introDuration=15330&adDuration=4000&postAdDuration=830&adKeys=talk=stanley_mcchrystal;year=2011;theme=war_and_peace;theme=a_taste_of_ted2011;theme=new_on_ted_com;event=New+on+TED.com;tag=Culture;tag=Global+Issues;tag=leadership;tag=peace;tag=war;"></embed>';

$videos[] = '<embed src="http://video.ted.com/assets/player/swf/EmbedPlayer.swf" pluginspace="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" wmode="transparent" bgColor="#ffffff" width="446" height="326" allowFullScreen="true" allowScriptAccess="always" flashvars="vu=http://video.ted.com/talk/stream/2011/Blank/DavidChristian_2011-320k.mp4&su=http://images.ted.com/images/ted/tedindex/embed-posters/DavidChristian-2011.embed_thumbnail.jpg&vw=432&vh=240&ap=0&ti=1118&lang=eng&introDuration=15330&adDuration=4000&postAdDuration=830&adKeys=talk=david_christian_big_history;year=2011;theme=a_taste_of_ted2011;theme=the_rise_of_collaboration;theme=peering_into_space;theme=presentation_innovation;theme=unconventional_explanations;theme=technology_history_and_destiny;event=Technology%2C+History+and+Destiny;tag=big+bang;tag=cosmos;tag=education;tag=history;tag=humanity;tag=internet;tag=universe;tag=visualizations;"></embed>';

$videos[] = '<embed src="http://video.ted.com/assets/player/swf/EmbedPlayer.swf" pluginspace="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" wmode="transparent" bgColor="#ffffff" width="446" height="326" allowFullScreen="true" allowScriptAccess="always" flashvars="vu=http://video.ted.com/talk/stream/2011/Blank/EricWhitacre_2011-320k.mp4&su=http://images.ted.com/images/ted/tedindex/embed-posters/EricWhitacre-2011.embed_thumbnail.jpg&vw=432&vh=240&ap=0&ti=1110&lang=eng&introDuration=15330&adDuration=4000&postAdDuration=830&adKeys=talk=eric_whitacre_a_virtual_choir_2_000_voices_strong;year=2011;theme=a_taste_of_ted2011;theme=the_creative_spark;theme=new_on_ted_com;event=New+on+TED.com;tag=Arts;tag=Entertainment;tag=music;"></embed>';

$videos[] = '<embed src="http://video.ted.com/assets/player/swf/EmbedPlayer.swf" pluginspace="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" wmode="transparent" bgColor="#ffffff" width="334" height="326" allowFullScreen="true" allowScriptAccess="always" flashvars="vu=http://video.ted.com/talks/dynamic/LisaGansky_2011S-medium.flv&su=http://images.ted.com/images/ted/tedindex/embed-posters/LisaGansky-2011S.embed_thumbnail.jpg&vw=320&vh=240&ap=0&ti=1077&lang=eng&introDuration=15330&adDuration=4000&postAdDuration=830&adKeys=talk=lisa_gansky_the_future_of_business_is_the_mesh;year=2011;theme=new_on_ted_com;theme=the_power_of_cities;theme=not_business_as_usual;event=Not+Business+as+Usual;tag=Business;tag=Technology;"></embed>';

?>
