
<?php 


$videos[] = '<embed src="http://video.ted.com/assets/player/swf/EmbedPlayer.swf" pluginspace="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" wmode="transparent" bgColor="#ffffff" width="446" height="326" allowFullScreen="true" allowScriptAccess="always" flashvars="vu=http://video.ted.com/talk/stream/2011A/Blank/MickEbeling_2011A-320k.mp4&su=http://images.ted.com/images/ted/tedindex/embed-posters/MickEbeling-2011A.embed_thumbnail.jpg&vw=432&vh=240&ap=0&ti=1115&lang=eng&introDuration=15330&adDuration=4000&postAdDuration=830&adKeys=talk=mick_ebeling_the_invention_that_unlocked_a_locked_in_ar;year=2011;theme=the_creative_spark;theme=art_unusual;theme=design_like_you_give_a_damn;theme=what_s_next_in_tech;theme=the_rise_of_collaboration;theme=tales_of_invention;event=Tales+of+Invention;tag=Design;tag=Technology;tag=creativity;tag=disease;tag=invention;tag=open-source;"></embed>';

$videos[] = '<embed src="http://video.ted.com/assets/player/swf/EmbedPlayer.swf" pluginspace="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" wmode="transparent" bgColor="#ffffff" width="446" height="326" allowFullScreen="true" allowScriptAccess="always" flashvars="vu=http://video.ted.com/talks/dynamic/JacksonBrowne_2010X-medium.flv&su=http://images.ted.com/images/ted/tedindex/embed-posters/JacksonBrowne-2010X.embed_thumbnail.jpg&vw=432&vh=240&ap=0&ti=1117&lang=eng&introDuration=15330&adDuration=4000&postAdDuration=830&adKeys=talk=jackson_browne_if_i_could_be_anywhere;year=2010;theme=the_creative_spark;theme=new_on_ted_com;theme=a_taste_of_mission_blue_voyage;theme=ocean_stories;event=Ocean+Stories;tag=Entertainment;tag=TED+Prize;tag=music;tag=ocean;"></embed>';

$videos[] = '<embed src="http://video.ted.com/assets/player/swf/EmbedPlayer.swf" pluginspace="http://www.macromedia.com/go/getflashplayer" type="application/x-shockwave-flash" wmode="transparent" bgColor="#ffffff" width="446" height="326" allowFullScreen="true" allowScriptAccess="always" flashvars="vu=http://video.ted.com/talks/SylviaEarle_2009-stream-Prize_xxlow.flv&su=http://images.ted.com/images/ted/tedindex/embed-posters/SylviaEarle-2009.embed_thumbnail.jpg&vw=432&vh=240&ap=0&ti=467&lang=eng&introDuration=21000&adDuration=0&postAdDuration=0&adKeys=talk=sylvia_earle_s_ted_prize_wish_to_protect_our_oceans;year=2009;theme=speaking_at_ted2009;theme=to_boldly_go;theme=the_creative_spark;theme=inspired_by_nature;theme=women_reshaping_the_world;theme=animals_that_amaze;theme=ted_prize_winners;theme=master_storytellers;event=Master+Storytellers;tag=Science;tag=TED+Prize;tag=TED2009;tag=activism;tag=biodiversity;tag=exploration;tag=oceans;"></embed>';

?>
